/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103Cx.h"
#include "stm32f103c6_gpio.h"
#include <LCD_DRIVER/lcd.h>
#include <KEYPAD_DRIVER/keypad.h>

/**
 * @brief 
 * 
 */

#define ZERO 0x01
#define ONE 0x79
#define TWO 0x24
#define THREE 0x30
#define FOUR 0x19
#define FIVE 0x12
#define SIX 0x02
#define SEVEN 0x4C
#define EIGHT 0x00
#define NINE 0x10

void RCC_CONFIGURE() {

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}

/**
 * @brief 
 * 
 */
void GPIO_CONFIGURE() {

	GPIO_config_t pinconfig;

	//PA1 input HighZ Floating input (reset state)
	//	pinconfig.PinNumber = GPIO_PIN_1;
	//	pinconfig.GpioMode = GpioMode_INPUT_FLO;
	//	MCAL_GPIO_INIT(GPIOA, &pinconfig);

	//PB1 (output PUSH pull Mode)
	//01: Output mode, max speed 10 MHz.
	//CNF 00: General purpose output push-pull
	pinconfig.PinNumber = GPIO_PIN9;
	pinconfig.GpioMode = GPIO_MODE_output_push_pull;
	pinconfig.GpioSpeed = GPIO_speed10MHz;
	MCAL_GPIO_INIT(GPIOB, &pinconfig);

	pinconfig.PinNumber = GPIO_PIN10;
	pinconfig.GpioMode = GPIO_MODE_output_push_pull;
	pinconfig.GpioSpeed = GPIO_speed10MHz;
	MCAL_GPIO_INIT(GPIOB, &pinconfig);

	pinconfig.PinNumber = GPIO_PIN11;
	pinconfig.GpioMode = GPIO_MODE_output_push_pull;
	pinconfig.GpioSpeed = GPIO_speed10MHz;
	MCAL_GPIO_INIT(GPIOB, &pinconfig);

	pinconfig.PinNumber = GPIO_PIN12;
	pinconfig.GpioMode = GPIO_MODE_output_push_pull;
	pinconfig.GpioSpeed = GPIO_speed10MHz;
	MCAL_GPIO_INIT(GPIOB, &pinconfig);

	pinconfig.PinNumber = GPIO_PIN13;
	pinconfig.GpioMode = GPIO_MODE_output_push_pull;
	pinconfig.GpioSpeed = GPIO_speed10MHz;
	MCAL_GPIO_INIT(GPIOB, &pinconfig);

	//============================

	//PA13 input HighZ Floating input (reset state)
	pinconfig.PinNumber = GPIO_PIN14;
	pinconfig.GpioMode = GPIO_MODE_output_push_pull;
	pinconfig.GpioSpeed = GPIO_speed10MHz;
	MCAL_GPIO_INIT(GPIOB, &pinconfig);
	//PB13 (output PUSH pull Mode)
	pinconfig.PinNumber = GPIO_PIN15;
	pinconfig.GpioMode = GPIO_MODE_output_push_pull;
	pinconfig.GpioSpeed = GPIO_speed10MHz;
	MCAL_GPIO_INIT(GPIOB, &pinconfig);

}

int main(void) {

	RCC_CONFIGURE();
	GPIO_CONFIGURE();
	LCD_INIT_ALL();
	KEYPAD_INIT();
	//LCD_WRITE_string("hey omar");
//	wait(500);
//	LCD_clear_screen();
	LCD_WRITE_string("7SEG mode");
	wait(500);
	LCD_clear_screen();
	unsigned char temp;
	unsigned char seg[] = { ZERO, ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN,
			EIGHT, NINE, ZERO };
	unsigned char lcd[] = { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
			'0' };
	for (int i = 0; i < 11; i++) {
		MCAL_GPIO_WRITEPORT(GPIOB, seg[i] << 9);
		LCD_WRITE_char(lcd[i]);
		wait(1000);
	}
	KEYPAD_INIT();
	LCD_clear_screen();
	LCD_WRITE_string("keypad mode");
	wait(500);
	LCD_clear_screen();
	while (1) {
		temp = KEYPAD_GETKEY();

		switch (temp) {
		case 'A':
			break;
		case '?':
			LCD_clear_screen();
			break;
		default:
			LCD_WRITE_char(temp);
			break;
		}
	}
	return 0;
}

