
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


#include "STM32F103Cx.h"
#include "stm32f103c6_gpio.h"







/**
 * @brief this is the program clock gonfiguration function to enable the clock for the gpio ports 
 * 
 */
void RCC_CONFIGURE() {


	RCC_GPIOA_CLK_EN() ;
	RCC_GPIOB_CLK_EN() ;
}

/**
 * @brief this is the program gonfiguration function to intialize the gpio pins
 * 
 */
void GPIO_CONFIGURE() {

	GPIO_config_t pinconfig ;


	///PORTA.PIN1 INPUT FLOATING MODE PULLUP resistor (SINGLE PRESS) (high z)
	pinconfig.GpioMode = GPIO_MODE_Floating_input ;
	pinconfig.PinNumber= GPIO_PIN1 ;
	MCAL_GPIO_INIT(GPIOA, &pinconfig);

	///PORTB.PIN1 OUTPUT PUSH-PULL
	pinconfig.GpioMode = GPIO_MODE_output_push_pull ;
	pinconfig.PinNumber= GPIO_PIN1 ;
	MCAL_GPIO_INIT(GPIOB, &pinconfig) ;

	///PORTA.PIN13 INPUT FLOATING MODE PULLUP resistor (SINGLE PRESS) (high z)
	pinconfig.GpioMode = GPIO_MODE_Floating_input ;
	pinconfig.PinNumber= GPIO_PIN13 ;
	MCAL_GPIO_INIT(GPIOA, &pinconfig);


	///PORTB.PIN13 OUTPUT PUSH-PULL
	pinconfig.GpioMode = GPIO_MODE_output_push_pull ;
	pinconfig.PinNumber= GPIO_PIN13 ;
	MCAL_GPIO_INIT(GPIOB, &pinconfig) ;


}



int main(void) {



	RCC_CONFIGURE() ;
	GPIO_CONFIGURE() ;

	while(1){
		//single press  EXTERNAL PUR

		if   (  MCAL_GPIO_READPIN(GPIOA, GPIO_PIN1)  == 0 )
		{

			MCAL_GPIO_togglePIN(GPIOB, GPIO_PIN1) ;
			while(MCAL_GPIO_READPIN(GPIOA, GPIO_PIN1) == 0 );

			for (int i = 0; i < 5000; i++);
		}
		//multi press  EXTERNAL PDR

		if  (   MCAL_GPIO_READPIN(GPIOA, GPIO_PIN13)== 1 )

		{
			//TOGGEL_BIT(gpioB_ODR, 13);
			MCAL_GPIO_togglePIN(GPIOB, GPIO_PIN13) ;
			for (int i = 0; i < 5000; i++);
		}


	}
	return 0;
}














